script_security 1
vrrp_script check_redis {
    script "/etc/keepalived/check_redis_master.sh"  # Path to your script
    interval 2                        # Check every 2 seconds
    timeout 2                         # Timeout for the script
    rise 2                            # Number of successes to consider the service healthy
    fall 2                            # Number of failures to consider the service unhealthy
}

vrrp_instance VI_1 {
    state BACKUP                      # Use MASTER for the primary node
    virtual_router_id 51
    interface ens32
    priority 100                      # Adjust priorities for other nodes
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass JkNdd5IdJYIWxYQA
    }
    virtual_ipaddress {
        192.168.20.63                # Virtual IP
    }
    track_script {
        check_redis                  # Track the health of Redis
    }
}
